# Generated by Django 3.0.6 on 2020-06-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start_time', models.DateField()),
                ('end_time', models.DateField()),
                ('user', models.CharField(max_length=200)),
                ('meal', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='larderItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200)),
                ('amount', models.FloatField(null=True)),
                ('unit', models.CharField(max_length=200)),
                ('price', models.FloatField(null=True)),
                ('price_unit', models.FloatField(null=True)),
                ('user', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='recipes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('difficulty', models.CharField(max_length=200)),
                ('ingredients', models.CharField(max_length=200)),
                ('method', models.CharField(max_length=1000)),
                ('preparation_time', models.CharField(max_length=200)),
                ('serves', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('image_url', models.CharField(max_length=200)),
            ],
        ),
    ]
